### ISSUE TITLE
Finger print extraction (Part 2): Software to read the fingerprint 

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/biometrics-seed-extraction#12]
### Task to solve
The requirement is to generate cryptographic keys from biometric data. The device ATECC608B as a part of CRYPTOAUTH TRUST PLATFORM DEVELOPMENT KIT uses advanced Elliptic Key Cryptography keys used in  public key cryptography operations like Encryption and Digital Signatures. ATECC608B provides wide range of symmetric and asymmetric cryptography capabilities and we aim to leverage this for AE- Biometric. 

### Solution
We set up the dependencies required for accessing ATECC608B through CRYPTOAUTH TRUST PLATFORM DEVELOPMENT KIT using cryptoauth library. We move step by step in the process by first accessing the MCU of the board using a simple program of lighting the LEDs. 

#### Hello World with MPLAB X and CRYPTOAUTH TRUST PLATFORM DEVELOPMENT KIT 
- [x] Set the compiler and simulator (for debugging) properties  in MPLAB X
- [x] Build MPLAB X project- "Lighting the LED" on MPLAB X IDE
- [x] Program the MCU using the compiled code of above project.
- [x] Build the full architecture/flow diagram to obtain the keys from the vectorized image.

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/biometrics-seed-extraction/12?planning-poker) with ZenHub @sauravkr-diat-ai @lucy-sha512 @I-Archer-Zero @nilesh-uniris

**Comment by lucy-sha512** [comment]
Received the cryptoprocessor from vendor.

**Comment by lucy-sha512** [comment]
Resolved  errors of xc8 compiler
